---
application:
  name: "node-role-base-login-microservice"
  project: "node microservice rolebase login"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "test"
  version: "4.4"
routers:
- name: "main-node-role-base-login-microservice"
  routes:
  - application_name: "node-role-base-login-microservice"
    paths:
    - "/*"
